config/routes.rb
Rails.application.routes.draw do

  get "/auth/:provider/callback", to: "sessions#create"
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root to: 'sessions#new'

  resources :users, only: [:show] do
    get "/following", to: "users/following#index"
    get "/starred", to: "users/starred#index"
    get "/followers", to: "users/followers#index"
    get "/repos", to: "users/repos#index"
    get "/organizations", to: "users/organizations#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commit.rb
class Commit
  attr_reader :url, :date, :name, :message, :repo_name

  def initialize(data)
    @url = data[:commit][:url]
    @date = data[:commit][:author][:date]
    @name = data[:commit][:author][:name]
    @message = data[:commit][:message]
    @repo_name = data[:repository][:name]
  end
end

app/models/github_presenter.rb
class GithubPresenter
  def initialize(current_user)
    @github_service = GithubService.new(current_user)
    @current_user = current_user
  end

  def followers
    @github_service.followers.map do |follower|
      GithubUser.new(follower, @current_user)
    end
  end

  def following
    @github_service.following.map do |following|
      GithubUser.new(following, @current_user)
    end
  end

  def starred
    @github_service.starred.count
  end

  def repos

    @github_service.repos.map do |repo|
      Repo.new(repo)
    end
  end

  def recent_commits
    @github_service.recent_commits[:items].map do |commit|
      Commit.new(commit)
    end
  end

  def organizations
    @github_service.organizations.map do |organization|
      Organization.new(organization)
    end
  end
end

app/models/github_user.rb
class GithubUser
  include ApplicationModule

  attr_reader :username, :uid, :avatar_url, :commits

  def initialize(data, current_user = nil)
    @username   = data[:login]
    @uid        = data[:uid]
    @avatar_url = data[:avatar_url]
    @current_user = current_user
  end

  def commits
    @commits ||= recent_commits
  end

  def recent_commits
    response = GithubService.new(@current_user).recent_commits(@username)
    validate_commits(response)
  end

  private

  def validate_commits(response)
    if response[:total_count] > 0
      response[:items].map do |commit|
        Commit.new(commit)
      end
    else
      "No recent commits"
    end
  end
end

app/models/organization.rb
class Organization
  attr_reader :login, :description, :id, :avatar_url

  def initialize(data)
    @login = data[:login]
    @description = data[:description]
    @id = data[:id]
    @avatar_url = data[:avatar_url]
  end
end

app/models/repo.rb
class Repo
  attr_reader :name, :language, :stargazers_count, :html_url, :created_at

  def initialize(data)
    @name = data[:name]
    @language = data[:language]
    @stargazers_count = data[:stargazers_count]
    @html_url = data[:html_url]
    @created_at = data[:created_at]
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.from_omniauth(auth)
    binding.pry
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.email = auth.info.email
      user.uid = auth.uid
      user.provider = auth.provider
      user.avatar_url = auth.info.image
      user.username = auth.info.name
      user.oauth_token = auth.credentials.token
      user.repos = auth.extra.raw_info.public_repos
      user.nickname = auth.info.nickname
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    binding.pry
    user = User.from_omniauth(request.env["omniauth.auth"])

    if user.valid?
      session[:user_id] = user.id
      redirect_to user_path(current_user)
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users/followers_controller.rb
class Users::FollowersController < ApplicationController
  def index
    @github_presenter = GithubPresenter.new(current_user)
  end
end

app/controllers/users/following_controller.rb
class Users::FollowingController < ApplicationController
  def index
    @github_presenter = GithubPresenter.new(current_user)
  end
end

app/controllers/users/organizations_controller.rb
class Users::OrganizationsController < ApplicationController
  def index
    @github_presenter = GithubPresenter.new(current_user)
  end

end

app/controllers/users/repos_controller.rb
class Users::ReposController < ApplicationController
  def index
    @github_presenter = GithubPresenter.new(current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @github_presenter = GithubPresenter.new(current_user)
  end
end

app/helpers/application_module.rb
module ApplicationModule
  def to_datetime(github_date)
    Time.parse(github_date).strftime("%Y-%m-%d")
  end

  def search_date
    1.week.ago.strftime("%Y-%m-%d")
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiCurious</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Abel|Roboto:900" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
  </head>

  <body>
    <%= render partial: "/partials/navbar" %>
    <main>
      <%= yield %>
    </main>
    <%= render partial: "/partials/footer" %>
  </body>
</html>

app/views/partials/_footer.html.erb
<footer>
  <p class="footer-text">created by <%= link_to "Keegan", "https://github.com/keegancorrigan/", class:"footer-link-text" %></p>
</footer>

app/views/partials/_navbar.html.erb
<div class="clearfix mb2 white navbar">
  <div class="navflex">
    <div class="left pl4">
      <i class="fab fa-github btn py2 m0"></i>
      <a href="#!" class="btn py2 m0">GrabCore</a>
    </div>
    <div class="right pr4 logout-button">
      <% if current_user %>
        <button type="button" class="btn btn-primary">
          <%= link_to "Profile", user_path(current_user), class:"link-reset" %>
        </button>
        <%= link_to "Logout", signout_path, class:"btn py2 m0" %>
      <% end %>
    </div>
  </div>
</div>

app/views/partials/_on_page_nav.html.erb
<div class="mxn1">
  <%= link_to "Followers", user_followers_path(current_user), class:"btn button-narrow"%> /
  <%= link_to "Following", user_following_path(current_user),class:"btn button-narrow" %> /
  <%= link_to "Repos", user_repos_path(current_user), class:"btn button-narrow" %> /
    <%= link_to "Organizations", user_organizations_path(current_user), class:"btn button-narrow" %>
</div>

app/views/partials/_profile_info.html.erb
  <%= image_tag current_user.avatar_url, class:"profile-image"  %>
  <h2><%= current_user.username %></h2>
  <h3><%= current_user.nickname %></h4>

  <p>
    Starred repos:
    <% @github_presenter.starred.times do %>
      <i class="fas fa-star"></i>
    <% end %>
  </p>

app/views/users/followers/index.html.erb
<div class="clearfix">

  <div class="sm-col sm-col-3">
  <%= render partial:"/partials/profile_info" %>
  </div>

  <div class="sm-col sm-col-9">
    <%= render partial: "/partials/on_page_nav" %>


  <h2>Followers</h2>
  <% @github_presenter.followers.each do |follower| %>

    <div class="followers clearfix flex items-center mb2">
      <div class="sm-col sm-col-3 follower-table">
        <div class="left mr1">
          <%= image_tag follower.avatar_url, class:"follower-image" %>
        </div>
        <div class="overflow-hidden">
          <p class="username"><%= follower.username %></p>
        </div>
      </div>

      <div class="sm-col sm-col-9">
        <div class="recent-commit follower-table-text">
          <% if follower.commits != "No recent commits" %>
            <p> <strong>Recent commit Message:</strong> <%= follower&.commits&.first&.message %></p>
            <p> <strong>Repo:</strong> <%= follower&.commits&.first&.repo_name %></p>
          <% else %>
            <p><strong> <%= follower.commits %> </strong></p>
            <p> Get back to work <%= follower.username %>! </p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/following/index.html.erb
<div class="clearfix">

  <div class="sm-col sm-col-3">
  <%= render partial:"/partials/profile_info" %>
  </div>

    <div class="sm-col sm-col-9">
      <%= render partial: "/partials/on_page_nav" %>


    <h2>Following</h2>


    <% @github_presenter.following.each do |follower| %>
    <div class="followers clearfix flex items-center mb2">
      <div class="sm-col sm-col-3 follower-table">
        <div class="left mr1">
          <%= image_tag follower.avatar_url, class:"follower-image" %>
        </div>
        <div class="overflow-hidden">
          <p class="username"><%= follower.username %></p>
        </div>
      </div>

      <div class="sm-col sm-col-9">
        <div class="recent-commit follower-table-text">
          <% if follower.commits != "No recent commits" %>
            <p> <strong>Recent commit Message:</strong> <%= follower&.commits&.first&.message %></p>
            <p> <strong>Repo:</strong> <%= follower&.commits&.first&.repo_name %></p>
          <% else %>
            <p><strong> <%= follower.commits %> </strong></p>
            <p> Get back to work <%= follower.username %>! </p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  </div>

app/views/users/organizations/index.html.erb
<div class="clearfix">

  <div class="sm-col sm-col-3">
  <%= render partial:"/partials/profile_info" %>
  </div>

  <div class="sm-col sm-col-9">
    <%= render partial: "/partials/on_page_nav" %>


    <h2>Organizations</h2>

    <% @github_presenter.organizations.each do |organization| %>
      <div class="organizations">
        <p class="login"><%= organization.login %></p>
        <p><%= organization.description %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/users/repos/index.html.erb
<div class="clearfix">

  <div class="sm-col sm-col-3">
  <%= render partial:"/partials/profile_info" %>
  </div>

  <div class="sm-col sm-col-9">
    <%= render partial: "/partials/on_page_nav" %>


    <h2>Repos</h2>

    <div class="clearfix">
      <div class="col col-3">
        <p> Name </p>
      </div>
      <div class="col col-2">
        <p> Language </p>
      </div>
      <div class="col col-2">
        <p> Created on </p>
      </div>
      <div class="col col-1">
        <p> Stargazers</p>
      </div>
    </div>

    <% @github_presenter.repos.each do |repo| %>
      <div class="repos">
        <div class="clearfix commit-row">
          <div class="col col-3">
            <p class="name"><%= link_to repo.name, repo.html_url, class:"repo-link-text" %></p>
          </div>
          <div class="col col-2">
            <% if repo.language == "Ruby" %>
                <p><i class="far fa-gem"></i>  <%= repo.language %></p>
            <% else %>
              <p><%= repo.language %></p>
            <% end %>
          </div>
          <div class="col col-2">
            <p><%= repo.created_at %></p>
          </div>
          <div class="col col-1">
            <p><%= repo.stargazers_count %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="clearfix">

  <div class="sm-col sm-col-3">
  <%= render partial:"/partials/profile_info" %>
  </div>

  <div class="sm-col sm-col-9">
    <%= render partial: "/partials/on_page_nav" %>

    <h2> Recent Commits </h2>
   <% @github_presenter.recent_commits.each do |commit| %>
   <div class="commit clearfix">
     <p class="message"><strong>Message:</strong> <%= commit.message %><p>
    </div>
    <div class="clearfix commit-row">
     <div class="col col-4">
       <p><strong>Date:</strong> <%= commit.date %><p>
      </div>
      <div class="col col-7">
       <p><strong>Repo:</strong> <%= commit.repo_name %></p>
      </div>
   </div>
   <% end %>
  </div>
</div>